### ISSUE TITLE
The renamed connections in circuit boxes don't show up in wiring mode

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15702]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15697

<div type='discussions-op-text'>

<sup>Originally posted by **MatthiasKunnen** March  2, 2025</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a circuit box has custom named input/output signals, opening that circuit box with the screwdriver, to connect it to external components, the inputs and outputs are called `SIGNAL_IN_[1-8]`, `SIGNAL_OUT_[1-8]`, respectively. I expected those to have the custom name.

#### Circuit box:
![Circuit box](https://github.com/user-attachments/assets/4d2c2188-bb39-4a51-9f00-0289254e3904)

#### Wiring mode
![Wiring mode](https://github.com/user-attachments/assets/5019df86-ed84-4b59-9610-53e7d96b722d)

### Reproduction steps

1. Create a circuit box in the editor
2. Open it
3. Right-click on the input, click on _Rename connections_, rename the connections, repeat for the output
4. Close the circuit box
5. Go into wiring mode and edit the wiring of the circuit box
6. See that the custom names are not used.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Both v1.7.7.0 (Winter Update) and v1.8.4.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Other info

Circuit box related discussions:
- #12920
- #13781
- #13117
- #15269

I wasn't quite sure if this is a feature request or bug report. Feel free to move it if necessary</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/b56eae028ac377e90974b4547ebd93d09f5c381d

**Comment by MatthiasKunnen** [comment]
Related PR: #15698. Linking just for reference.

I actually did not notice that you opened this issue. Dicussions do not get an auto-link when they are referenced from issues apparrently.

**Comment by Regalis11** [comment]
Merged, closing

**Comment by Destroyanad** [comment]
Has this fix been applied to the game? My connects are still not renamed. Also the connection names inside the circuit box gets reset when copy-pasting

![Image](https://github.com/user-attachments/assets/020fd0b3-c776-4c56-9ad9-550051ae651e)

![Image](https://github.com/user-attachments/assets/0f2aa615-47d7-432a-828b-7d7c53c930ce)

**Comment by Destroyanad** [comment]
> This did not make it into the latest update according to [#15697 (comment)](https://github.com/FakeFishGames/Barotrauma/discussions/15697#discussioncomment-12522103).
> 
> For the copying of the circuit box, that's a separate issue, see [#15269](https://github.com/FakeFishGames/Barotrauma/discussions/15269).

Thank you
